### PR TITLE
Added proxy state + hibernation support

### PR DESCRIPTION
**Pull request by define-null**
In this pull request a new state "proxy" is introduced to give an opportunity dynamically switch from synchronized mode using active/notify to "proxy" mode when msgs are send as soon as they arrive to PO Box(both sending those which exist in the buffer if any). This is done in order to reduce amount of messages between PO Box and consumer when the load is low. The other functionality remains the same. Also I added support for hibernation of PO Box process and fixed an inaccuracy in the active/3 doc.

### CODE REVIEW

**Comment by define-null** [comment]
Sorry for long silence, we do not use pobox in production any more, as the overhead of one process for each consumer is to much for our needs. Your vision is correct, and please feel free to decline or approve this pullrequest according to your vision on the project.

**Comment by ferd** [comment]
I also had forgot of this PR. I'll have to think it through. My worry is that it's not necessarily the right solution to the problem. I.e. if the issue was that you needed one per process and it used too much memory, would it be better to have some abstract fanout structure supported instead?

What did you end up using in the end?

**Comment by define-null** [comment]
@ferd we end up implementing simple backpressure protocol, in brief:
Each producer send at most M messages to the consumer and check if {sync, N} message arrived where N is chosen by the consumer, but equal to M/2 by default. Consumer specify M limit to the producer and commit every N messages. Producer stop sending only if M messages were already sent but no sync arrived. Producer decides whether to drop messages, or replace new/old.

Instead of separate processes, backpressure is hidden in the abstraction named pipes (simple  framework), so while implementing concrete consumers and producers programmer only specifies backpressure options and sometimes implement parts of the protocol on the boundaries of the system.

Also i would like to add, that in our case there is often not one consumer, but several chained workers per producer(and plenty of producers), that filter/modify passing messages, so it becomes crucial to implement backpressure on the processes, that actually do some work.

**Comment by ferd** [comment]
Right. Backpressure sounds like a much better mechanism for your use case.
Glad to know you got a working solution!

**Pull request closed without merging**
