### PR TITLE
Make buffer implementation pluggable

### PR DESCRIPTION
**Pull request by edescourtis**
NOTE: This is a work in progress intended only for review.

How does something like this look?

### CODE REVIEW

**Comment by ferd** [comment]
Yeah that sounds good to me. Plus we can probably test it easy by making a sample buffer that's just the queue module and ensuring it works like the existing queue option

**Comment by ferd** [comment]
My initial reaction would be to say no because I'd believe things need to be simple, but I guess `{mod, Mod, Args}` could potentially work. It just means that the default buffers couldn't be implemented without a shim because they don't take arguments, so that's not a 100% match between semantics I guess.

**Comment by edescourtis** [comment]
Okay, I won't include it in this version but we can always add it later.

**Comment by edescourtis** [comment]
Take a look at this commit. Tell me if it's okay with you.

**Comment by ferd** [comment]
Cool, I'll try to take some time for this around the week-end. I've got a lot of OTP-21 prepardness to do first, but that should be on my list as well.

**Comment by edescourtis** [comment]
Let me know if you need help with anything.

**Comment by ferd** [comment]
Merged, re-versionned to 1.1.0, and published to hex + tagged.

**Pull request merged**
